version: '3.7'
services: 
  db:
    image: mysql:5.6
    # データの永続化領域(コンテナを破棄しても保存される場所)
    # ホスト側のディレクトリをvolumeとして、コンテナ内にマウント
    # 複数のコンテナ間から参照できるvolumeも作成できる
    volumes: 
      # delegated : コンテナ上の更新がホスト上に反映されるまでの遅延を許容する代わりに高速にする
      - db-volume:/var/lib/mysql:delegated
    # environment: 
    #   MYSQL_ROOT_PASSWARD: password
    # 環境変数定義ファイルを指定
    env_file: .env
    # 接続ポート（ホスト:コンテナ）
    ports: 
      # - 3306:3306
      - 4306:3306
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    # -b でコンテナ外からのアクセス許可
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # tty, stdin_open : -it オプションでコンテナに入って作業するための設定
    # コンテナを止めずに動かす(フォアグランドのプロセスが生き続ける)
    tty: true
    stdin_open: true
    # 環境変数定義ファイルを指定
    env_file: .env
    depends_on: 
      - db
    ports: 
      - '3000:3000'
    volumes: 
      - .:/app:cached
      - bundle:/usr/local/bundle:delegated
      - node_modules:/app/node_modules
      - tmp-data:/app/tmp/sockets

volumes: 
  # ホスト上の具体的なパスは基本的に指定しない
  # ボリュームの実体はデフォルトで「/var/lib/docker/volumes/db-volume/_data/」になる
  db-volume:
  bundle:
  node_modules:
  tmp-data:
